In [12]:
%matplotlib inline  

#One thing's for sure: that's a big array. In fact, it's lagging so badly it's hard to do anything now. Welp

#(After a while)
#Ok, let's just import something from a library instead

import matplotlib.pyplot as plt
import numpy as np
from cmath import exp, pi
from PIL import Image as im #Here we go


def dft(y):
    '''
    This is a code to do decrete Fourier transform
    '''    
    N = len(y)
    c = np.zeros(N, complex)
    for k in range(N):
        for n in range(N):
            c[k] += y[n]*exp(-2j*pi*k*n/N)
    return c

def idft(c):
    '''
    This is a code to do inverse Fourier transform
    '''
    N = len(c)
    y = np.zeros(N, complex)
    for k in range(N):
        for n in range(N):
            y[k] += c[n]*exp(2j*pi*k*n/N)
    return y
pic_array = np.arange(0, 737280, 1, np.uint8)
pic_array = np.reshape(pic_array, (1024, 720))
data = im.fromarray(pic_array)
print(array)
#data.save("gfg_dummy_pic.jpeg")

#Taking advantage of predefined functions, I can compress the process into a few lines. However, I did use a different
#array than the one provided: one that was already set to work with the functions. I wasn't able to figure out how to
#convert a bunch of random numbers into an image. However, it's obvious that the arrays are disgustingly large compared
#to the compressed versions and images. Looking at wikipedia for further reference, the compressed images go down to only
#a small percent of what the uncompressed ones were while still looking good, though there's a point where enough is enough.

'''
f = lambda x: 2*np.sin(x) + 1.5*np.cos(2*x) + np.sin(3*x)


left, right = 0,20
grain = 200


x = np.linspace(left,right,grain)
y = pic_array #Hopefully this works


c = dft(y)    
y1 = idft(c).real/grain 

#plot stuff
plt.plot(x,y, 'b*', label='noisy data')
plt.plot(x,f(x), 'r--', label='original function')
plt.plot(x,y1, 'y', label='idft')

plt.xlabel('x')
plt.ylabel('$f(x)$')
plt.xlim([left, right])
plt.legend(loc='lower left')
plt.show()


fig, ax1 = plt.subplots()
ax1.plot(np.abs(c), 'b-', label='Magnitude')

ax2 = ax1.twinx()
ax2.plot(np.angle(c), 'r.-', label='Phase')
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')
plt.show()
'''

[[  0   1   2 ... 205 206 207]
 [208 209 210 ... 157 158 159]
 [160 161 162 ... 109 110 111]
 ...
 [144 145 146 ...  93  94  95]
 [ 96  97  98 ...  45  46  47]
 [ 48  49  50 ... 253 254 255]]


"\nf = lambda x: 2*np.sin(x) + 1.5*np.cos(2*x) + np.sin(3*x)\n\n\nleft, right = 0,20\ngrain = 200\n\n\nx = np.linspace(left,right,grain)\ny = pic_array #Hopefully this works\n\n\nc = dft(y)    \ny1 = idft(c).real/grain \n\n#plot stuff\nplt.plot(x,y, 'b*', label='noisy data')\nplt.plot(x,f(x), 'r--', label='original function')\nplt.plot(x,y1, 'y', label='idft')\n\nplt.xlabel('x')\nplt.ylabel('$f(x)$')\nplt.xlim([left, right])\nplt.legend(loc='lower left')\nplt.show()\n\n\nfig, ax1 = plt.subplots()\nax1.plot(np.abs(c), 'b-', label='Magnitude')\n\nax2 = ax1.twinx()\nax2.plot(np.angle(c), 'r.-', label='Phase')\nax1.legend(loc='upper left')\nax2.legend(loc='upper right')\nplt.show()\n"